<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251125152149 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE cena_produktu (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, produkt_id INT DEFAULT NULL, kwota INT NOT NULL, waluta_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE grupy_uzytkownikow (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, group_name VARCHAR(128) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE opinie (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, produkt_id INT NOT NULL, pozytywna BOOLEAN NOT NULL, tresc VARCHAR(512) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE produkty (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nazwa VARCHAR(255) DEFAULT NULL, opis VARCHAR(1024) DEFAULT NULL, zdjecie VARCHAR(512) DEFAULT NULL, cena DOUBLE PRECISION NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE uzytkownicy (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(128) NOT NULL, email VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, typeofuser BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE waluta (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, kod_iso VARCHAR(128) DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE zamowienia (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, delivery_id INT NOT NULL, uzytkownik_id INT NOT NULL, dostarczono BOOLEAN DEFAULT NULL, PRIMARY KEY (id))');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE cena_produktu');
        $this->addSql('DROP TABLE grupy_uzytkownikow');
        $this->addSql('DROP TABLE opinie');
        $this->addSql('DROP TABLE produkty');
        $this->addSql('DROP TABLE uzytkownicy');
        $this->addSql('DROP TABLE waluta');
        $this->addSql('DROP TABLE zamowienia');
    }
}
